#!/usr/bin/python3
import time

body = f"""<!DOCTYPE html>
<html>
<head><title>CGI Python</title></head>
<body>
    <h1>CGI Success!</h1>
    <p>Generated by Python at {time.ctime()}</p>
</body>
</html>"""

print("Status: 200 OK")
print("Content-Type: text/html; charset=utf-8")
print(f"Content-Length: {len(body.encode('utf-8'))}")
print()

print(body)